import {db} from './db.js';
import {chapterId} from '../data/syllabus.js';
const starter=[
 ['History',0,'Which source is especially useful for reconstructing Harappan craft production?',['Archaeological remains','Parliamentary debates','Modern census reports','Colonial newspapers'],0,'Archaeological remains can reveal workshops, tools, materials and finished objects.'],
 ['History',1,'In early Indian history, a janapada was primarily associated with:',['A territorial polity','A temple ritual','A guild of artists','A tax on trade'],0,'Janapadas were territorial polities that developed in early historic India.'],
 ['Geography',1,'Which factor most directly affects population distribution?',['Availability of water and resources','Colour of soil alone','Political slogans','Language scripts'],0,'Water, relief, climate, resources and economic opportunities influence settlement.'],
 ['Geography',2,'Human development is commonly assessed through indicators related to:',['Health, education and income','Only agricultural output','Only population size','Only exports'],0,'Human development focuses on capabilities and well-being.'],
 ['Political Science',0,'The end of bipolarity refers primarily to the collapse of:',['The Soviet Union-led bloc structure','The United Nations','The European Union','The Non-Aligned Movement'],0,'The disintegration of the Soviet Union ended the Cold War bipolar structure.'],
 ['Political Science',1,'Which is an example of a contemporary centre of power?',['European Union','Harappan civilisation','Mauryan Empire','League of Nations'],0,'The European Union is discussed as a contemporary regional centre of power.'],
 ['English',0,'The Last Lesson primarily highlights the value of:',['Language and cultural identity','Industrialisation','Adventure tourism','Scientific discovery'],0,'The story connects language with identity, memory and cultural belonging.'],
 ['English',2,'In Keeping Quiet, the poet asks people to pause mainly to encourage:',['Introspection and reflection','Permanent inactivity','Economic competition','Military expansion'],0,'The poem uses stillness as an opportunity for introspection.'],
 ['Hindi',0,'भक्तिन के चरित्र में प्रमुख रूप से कौन-सा गुण उभरता है?',['कर्मठता और आत्मसम्मान','आलस्य','अत्यधिक विलासिता','असामाजिकता'],0,'भक्तिन के जीवन-संघर्ष में कर्मठता और स्वाभिमान दिखाई देता है.'],
 ['Hindi',1,'बाजार दर्शन पाठ मुख्यतः किस प्रवृत्ति पर विचार करता है?',['बाजारवाद और उपभोक्ता मानसिकता','केवल कृषि उत्पादन','प्राकृतिक आपदा','ऐतिहासिक युद्ध'],0,'पाठ बाजार की आकर्षण-शक्ति और उपभोक्ता मानसिकता पर विचार करता है.']
];
const online=[
 ['Political Science','polsci-01','The end of bipolarity in international politics led to an increase in ________.',['Proxy wars between super powers','Arms race between super powers','Multilateral diplomacy and cooperation','Bipolarity in international politics'],2,'Based on CBSE Class XII Political Science SQP 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/PolSci-SQP.pdf'],
 ['Political Science','polsci-06','Agenda-21 is related to which one of the following?',['Rio Summit','Antarctic Treaty','Montreal Protocol','Antarctic Environmental Protocol'],0,'Based on CBSE Class XII Political Science SQP 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/PolSci-SQP.pdf'],
 ['Geography','geography-01','In the CBSE Class XII Geography 2025-26 sample paper, Section A contains how many multiple-choice questions?',['10','12','17','20'],2,'Based on CBSE Class XII Geography SQP 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Geography-SQP.pdf'],
 ['Geography','geography-09','In the CBSE Class XII Geography 2025-26 sample paper, map-based questions are placed in which section?',['Section A','Section B','Section C','Section E'],3,'Based on CBSE Class XII Geography SQP 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/Geography-SQP.pdf'],
 ['English','english-01','The 2025-26 CBSE English Core sample paper contains which three sections?',['Reading Skills, Creative Writing Skills, Literature','Reading, Grammar, Translation','Literature, Speaking, Listening','Writing, Grammar, Vocabulary'],0,'Based on CBSE Class XII English Core SQP 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/EnglishCore-SQP.pdf'],
 ['English','english-02','What is the maximum mark of the CBSE Class XII English Core 2025-26 sample paper?',['70','75','80','100'],2,'Based on CBSE Class XII English Core SQP 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/EnglishCore-SQP.pdf'],
 ['Hindi','hindi-20','हिंदी कोर 2025-26 के पाठ्यक्रम में प्रश्न-पत्र कितने खंडों में विभाजित है?',['दो','तीन','चार','पाँच'],1,'Based on CBSE Hindi Core curriculum 2025-26.','https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Hindi_Core_SrSec_2025-26.pdf'],
 ['Hindi','hindi-20','हिंदी कोर 2025-26 में खंड-क मुख्यतः किस पर आधारित है?',['अपठित बोध','केवल व्याकरण','केवल लेखन','केवल साहित्यिक इतिहास'],0,'Based on CBSE Hindi Core curriculum 2025-26.','https://cbseacademic.nic.in/web_material/CurriculumMain26/SrSec/Hindi_Core_SrSec_2025-26.pdf'],
 ['History','history-01','Which site is identified as the correct answer to Question 1 in the CBSE Class XII History 2025-26 marking scheme?',['Lothal','Pataliputra','Taxila','Sanchi'],0,'Based on CBSE Class XII History Marking Scheme 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/History-MS.pdf'],
 ['History','history-03','Which text is given as the answer to Question 5 in the CBSE Class XII History 2025-26 marking scheme?',['Manusmriti','Arthashastra','Indica','Rajatarangini'],0,'Based on CBSE Class XII History Marking Scheme 2025-26.','https://cbseacademic.nic.in/web_material/SQP/ClassXII_2025_26/History-MS.pdf'],
 ['Political Science','polsci-04','Which CBSE Class XII resource page lists Sample Question Papers and Marking Schemes for 2025-26 across subjects?',['Class XII SQP and MS page','Admissions portal','Results portal','Scholarship portal'],0,'CBSE Academics Class XII SQP/MS 2025-26.','https://cbseacademic.nic.in/SQP_CLASSXII_2025-26.html'],
 ['History','history-12',"CBSE's previous-year question paper page provides Class XII examination papers for subjects including History, Geography, English Core, Hindi Core and Political Science.",['True','False','Only for Class X','Only for vocational subjects'],0,"CBSE Previous Years' Question Papers.",'https://www.cbse.gov.in/cbsenew/question-paper.html']
];
const make=(q,i)=>({id:'practice-seed-'+(i+1),format:'mcq',text:q[2],options:q[3],correct_index:q[4],explanation:q[5],subject:q[0],chapter_id:chapterId(q[0],q[1]),difficulty:i%3===0?'easy':i%3===1?'medium':'hard',qtype:'standard',marks:1,source:'practice',tags:['starter','practice']});
const makeOnline=(q,i)=>({id:'online-feed-'+(i+1),format:'mcq',text:q[2],options:q[3],correct_index:q[4],explanation:q[5],subject:q[0],chapter_id:q[1],difficulty:i%3===0?'easy':i%3===1?'medium':'hard',qtype:'standard',marks:1,source:'ai_generated',reference:q[6],tags:['online-feed','cbse-reference']});
export async function ensureQuestionBank(){
 const all=await db.all('questions'),existing=new Set(all.map(q=>q.id));
 for(let i=0;i<starter.length;i++){const q=make(starter[i],i);if(!existing.has(q.id))await db.put('questions',q);}
 for(let i=0;i<online.length;i++){const q=makeOnline(online[i],i);if(!existing.has(q.id))await db.put('questions',q);}
 return db.all('questions');
}