import {db} from '../services/db.js';
import {SUBJ_KEYS} from '../data/syllabus.js';
import {$,esc,toast} from '../utils/dom.js';
let qs=[]; let state=null;
const today=()=>new Date().toISOString().slice(0,10);
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
async function load(){qs=(await db.all('questions')).filter(q=>q.format!=='mcq');}
function setup(root){root.innerHTML=`<div class="answer-toolbar"><div><span class="lbl">ANSWER WRITING PRACTICE</span><h3 class="answer-title">Write like you will in the examination.</h3></div></div><div class="answer-config"><label><span class="lbl">SUBJECT</span><select data-sub>${SUBJ_KEYS.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}</select></label><label><span class="lbl">QUESTION</span><select data-q></select></label><label><span class="lbl">TIME</span><select data-time><option value="600">10 min</option><option value="900" selected>15 min</option><option value="1200">20 min</option><option value="1800">30 min</option></select></label></div><div data-preview></div><button class="btn solid" data-start>START WRITING</button>`;
 const sub=root.querySelector('[data-sub]'), qsel=root.querySelector('[data-q]');
 const refresh=()=>{const list=qs.filter(q=>q.subject===sub.value);qsel.innerHTML=list.length?list.map(q=>`<option value="${q.id}">${esc(q.text.slice(0,110))} · ${q.marks} marks</option>`).join(''):'<option value="">No written questions yet</option>';root.querySelector('[data-preview]').textContent=list.length?`${list.length} written questions available · suggested word limit ${Math.round((list[0]?.marks||3)*35)}–${Math.round((list[0]?.marks||3)*45)} words`:'Add short/long practice questions to begin.'};
 sub.onchange=refresh;refresh();root.querySelector('[data-start]').onclick=()=>start(root,qsel.value,Number(root.querySelector('[data-time]').value));}
function start(root,id,duration){const q=qs.find(x=>x.id===id);if(!q){toast('No written question selected');return;}state={q,duration,started:Date.now(),remaining:duration,timer:null};state.timer=setInterval(()=>{state.remaining--;const el=root.querySelector('[data-clock]');if(el)el.textContent=fmt(Math.max(0,state.remaining));if(state.remaining<=0)finish(root,true)},1000);render(root);}
function render(root){const q=state.q;root.innerHTML=`<div class="answer-live"><div class="answer-question"><span class="lbl">${esc(q.subject)} · ${q.marks} MARKS</span><h3>${esc(q.text)}</h3><p class="answer-meta">Suggested word limit: ${Math.round(q.marks*35)}–${Math.round(q.marks*45)} words</p></div><div class="answer-clock"><span class="lbl">TIME LEFT</span><strong data-clock>${fmt(state.remaining)}</strong></div></div><textarea data-answer maxlength="20000" placeholder="Write your answer here…"></textarea><div class="answer-tools"><span data-words>0 words</span><span>Self-check before saving</span></div><div class="answer-check"><label><input type="checkbox" data-check="introduction"> Introduction</label><label><input type="checkbox" data-check="points"> Main points</label><label><input type="checkbox" data-check="keywords"> Keywords</label><label><input type="checkbox" data-check="examples"> Examples</label><label><input type="checkbox" data-check="conclusion"> Conclusion</label><label><input type="checkbox" data-check="word_limit"> Word limit</label></div><div class="answer-actions"><button class="btn" data-cancel>DISCARD</button><button class="btn solid" data-save>SAVE ATTEMPT</button></div>`;
 const ta=root.querySelector('[data-answer]');ta.oninput=()=>{const n=ta.value.trim()?ta.value.trim().split(/\s+/).length:0;root.querySelector('[data-words]').textContent=`${n} words`;};root.querySelector('[data-cancel]').onclick=()=>{clearInterval(state.timer);state=null;setup(root)};root.querySelector('[data-save]').onclick=()=>finish(root,false);}
async function finish(root,auto){if(!state)return;clearInterval(state.timer);const ta=root.querySelector('[data-answer]');const text=ta?.value||'';const word_count=text.trim()?text.trim().split(/\s+/).length:0;const checklist={};root.querySelectorAll('[data-check]').forEach(x=>checklist[x.dataset.check]=x.checked);const previous=(await db.query('answers','question_id',state.q.id)).length;await db.put('answers',{question_id:state.q.id,date:today(),text,word_count,time_sec:Math.round((Date.now()-state.started)/1000),attempt_no:previous+1,checklist});const day=await db.get('daily_activity',today());await db.put('daily_activity',{id:today(),date:today(),study_sec:day?.study_sec||0,questions:(day?.questions||0)+1,correct:day?.correct||0,pyqs:day?.pyqs||0,revisions:day?.revisions||0,tests:day?.tests||0,missions_done:day?.missions_done||0});root.innerHTML=`<div class="answer-result"><span class="lbl">${auto?'TIME EXPIRED · SAVED':'ANSWER SAVED'}</span><strong>${word_count} words</strong><p>Your attempt has been stored locally. You can review and improve it later.</p><button class="btn solid" data-again>WRITE ANOTHER</button></div>`;root.querySelector('[data-again]').onclick=()=>setup(root);toast('Answer attempt saved');state=null;}
export async function initAnswerWriting(){const root=$('#answerWritingApp');if(!root)return;await load();setup(root);}
