import {db} from '../../services/db.js';
import {SUBJ_KEYS,allChapters} from '../../data/syllabus.js';
import {$,esc,toast} from '../../utils/dom.js';
let questions=[];
const today=()=>new Date().toISOString().slice(0,10);
const official=q=>q.source==='official_pyq';
const sourceLabel=q=>official(q)?`CBSE PYQ · ${q.year}${q.board?` · ${q.board}`:''}`:'PRACTICE · NOT AN OFFICIAL PYQ';
const escQ=s=>esc(String(s??''));
async function load(){
  questions=(await db.all('questions')).filter(q=>q.format!=='mcq');
  if(!questions.length){
    const seed=[
      ['History','history-11','Analyse the major features of the Civil Disobedience Movement.','3'],
      ['Geography','geography-12','Explain any three measures for conservation and management of water resources.','3'],
      ['Political Science','polsci-07','Explain any three consequences of globalisation for developing countries.','3'],
      ['English','english-05','How does Indigo present the relationship between peasants and the freedom movement?','5'],
      ['Hindi','hindi-02','‘बाज़ार व्यक्ति को आकर्षित भी करता है और प्रभावित भी।’ पाठ के आधार पर स्पष्ट कीजिए।','3']
    ];
    for(const [subject,chapter_id,text,marks] of seed){
      await db.put('questions',{format:'short',text,options:[],answer:'',explanation:'Practice question added as a safe local starter. It is not an official CBSE PYQ.',subject,chapter_id,difficulty:'medium',qtype:'conceptual',marks:Number(marks),source:'practice',tags:['starter','practice']});
    }
    questions=(await db.all('questions')).filter(q=>q.format!=='mcq');
  }
}
function card(q){return `<article class="pyq-card"><div class="pyq-meta"><span class="chip">${escQ(q.subject)}</span><span class="chip">${q.marks} MARK${q.marks==1?'':'S'}</span><span class="chip ${official(q)?'verified':''}">${escQ(sourceLabel(q))}</span></div><h3>${escQ(q.text)}</h3>${q.reference?`<p class="muted">Source: ${escQ(q.reference)}</p>`:''}<div class="pyq-actions"><button class="btn" data-act="attempt" data-id="${q.id}">MARK SOLVED</button><button class="btn" data-act="bookmark" data-id="${q.id}">BOOKMARK</button><button class="btn" data-act="mistake" data-id="${q.id}">ADD TO MISTAKES</button></div><div class="pyq-self hidden" data-self="${q.id}"><span class="lbl">SELF-RATE</span><div class="rating-row">${[['didnt_know','DIDN’T KNOW'],['partial','PARTIAL'],['knew','KNEW'],['excellent','EXCELLENT']].map(([v,t])=>`<button class="btn" data-rating="${v}" data-id="${q.id}">${t}</button>`).join('')}</div></div></article>`}
async function attempt(q,rating=null){await db.put('attempts',{question_id:q.id,date:today(),subject:q.subject,chapter_id:q.chapter_id,context:'daily_pyq',selected:null,correct:null,self_rating:rating,time_sec:0});const d=await db.get('daily_activity',today());await db.put('daily_activity',{id:today(),date:today(),study_sec:d?.study_sec||0,questions:d?.questions||0,correct:d?.correct||0,pyqs:(d?.pyqs||0)+1,revisions:d?.revisions||0,tests:d?.tests||0,missions_done:d?.missions_done||0});toast(rating?'PYQ saved':'Attempt saved — rate it below')}
async function toggleBookmark(q){const x=(await db.all('bookmarks')).find(b=>b.question_id===q.id);if(x){await db.remove('bookmarks',x.id);toast('Bookmark removed')}else{await db.put('bookmarks',{question_id:q.id,category:'important'});toast('Bookmarked')}}
async function addMistake(q){const x=(await db.all('mistakes')).find(m=>m.question_id===q.id);if(x)await db.update('mistakes',x.id,{times_wrong:x.times_wrong+1,last_attempted:new Date().toISOString(),mastered:false});else await db.put('mistakes',{question_id:q.id,subject:q.subject,chapter_id:q.chapter_id,times_wrong:1,correct_streak:0,last_attempted:new Date().toISOString(),mastered:false});toast('Added to Mistakes')}
function bind(root){root.addEventListener('click',async e=>{const b=e.target.closest('[data-act]');if(b){const q=questions.find(x=>x.id===b.dataset.id);if(!q)return;if(b.dataset.act==='attempt'){await attempt(q);root.querySelector(`[data-self="${q.id}"]`)?.classList.remove('hidden')}else if(b.dataset.act==='bookmark')await toggleBookmark(q);else await addMistake(q);return}const r=e.target.closest('[data-rating]');if(r){const q=questions.find(x=>x.id===r.dataset.id);if(q)await attempt(q,r.dataset.rating);r.closest('.pyq-self')?.classList.add('hidden')}})}
function filters(root){const s=root.querySelector('[data-subject]').value,c=root.querySelector('[data-chapter]').value,m=root.querySelector('[data-marks]').value,src=root.querySelector('[data-source]').value;return questions.filter(q=>(!s||q.subject===s)&&(!c||q.chapter_id===c)&&(!m||String(q.marks)===m)&&(!src||q.source===src))}
function renderBank(root){const list=filters(root);root.querySelector('[data-count]').textContent=`${list.length} questions`;root.querySelector('[data-results]').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>No matching questions.</h3><p>Change the filters or add verified questions to the local bank.</p></div>`}
function initBank(root){root.innerHTML=`<div class="pyq-filters"><label><span class="lbl">SUBJECT</span><select data-subject><option value="">All subjects</option>${SUBJ_KEYS.map(s=>`<option>${escQ(s)}</option>`).join('')}</select></label><label><span class="lbl">CHAPTER</span><select data-chapter><option value="">All chapters</option></select></label><label><span class="lbl">MARKS</span><select data-marks><option value="">All marks</option>${[1,2,3,4,5,6].map(n=>`<option value="${n}">${n} mark${n===1?'':'s'}</option>`).join('')}</select></label><label><span class="lbl">SOURCE</span><select data-source><option value="">All sources</option><option value="official_pyq">Official / verified PYQ</option><option value="practice">Practice</option><option value="ai_generated">AI-generated practice</option><option value="user_created">User-created</option></select></label></div><div class="pyq-summary"><span class="lbl" data-count>0 questions</span><span class="muted">Official PYQs retain their verified year/reference; generated questions are never presented as official.</span></div><div data-results></div>`;const refreshCh=()=>{const s=root.querySelector('[data-subject]').value;root.querySelector('[data-chapter]').innerHTML='<option value="">All chapters</option>'+allChapters().filter(c=>!s||c.subject===s).map(c=>`<option value="${c.id}">${escQ(c.name)}</option>`).join('');renderBank(root)};root.querySelectorAll('select').forEach(x=>x.onchange=refreshCh);root.querySelector('[data-chapter]').onchange=()=>renderBank(root);bind(root);refreshCh()}
function renderDaily(root){const pool=questions.filter(official).length?questions.filter(official):questions;if(!pool.length){root.innerHTML='<div class="empty"><h3>No PYQs loaded yet.</h3><p>The Daily PYQ module is ready. Verified questions can be added without changing the app architecture.</p></div>';return}const q=pool[Math.floor(Date.now()/86400000)%pool.length];root.innerHTML=`<div class="pyq-daily-head"><div><span class="lbl">${official(q)?'VERIFIED SOURCE':'SAFE FALLBACK'}</span><h3>Today’s question</h3></div><span class="chip">${escQ(sourceLabel(q))}</span></div>${card(q)}<p class="pyq-note">${official(q)?'Year and board/reference metadata are stored with this question.':'No verified PYQ was available locally, so this question is explicitly marked practice and is not an official CBSE PYQ.'}</p>`;bind(root)}
export async function initPYQ(){await load();const d=$('#dailyPyqApp'),b=$('#pyqBankApp');if(d)renderDaily(d);if(b)initBank(b)}
