/* Step 5 — reusable MCQ engine. Seeded questions are explicitly practice questions, never PYQs. */
import {SUBJ_KEYS,SUBJECTS,chapterId} from '../../data/syllabus.js';
import {db} from '../../services/db.js';
import {ensureQuestionBank} from '../../services/question-bank.js';
import {esc,toast,$} from '../../utils/dom.js';

let questions=[],current=[],index=0,score=0,locked=false,filter={subject:'',difficulty:''};

async function ensureSeed(){return ensureQuestionBank();}
function filtered(){return questions.filter(q=>(!filter.subject||q.subject===filter.subject)&&(!filter.difficulty||q.difficulty===filter.difficulty));}
function renderQuestion(root){const q=current[index];if(!q){root.innerHTML='<div class="empty"><h3>No questions available</h3><p>Try another filter.</p></div>';return;}root.querySelector('[data-qno]').textContent=`QUESTION ${index+1} / ${current.length}`;root.querySelector('[data-qtext]').textContent=q.text;root.querySelector('[data-meta]').textContent=`${q.subject} · ${q.difficulty.toUpperCase()} · ${q.source==='practice'?'PRACTICE':'VERIFIED SOURCE'}`;const box=root.querySelector('[data-options]');box.innerHTML=q.options.map((o,i)=>`<button class="mcq-option" data-option="${i}"><b>${String.fromCharCode(65+i)}</b><span>${esc(o)}</span></button>`).join('');root.querySelector('[data-feedback]').hidden=true;root.querySelector('[data-next]').disabled=true;locked=false;}
async function choose(root,i){if(locked)return;locked=true;const q=current[index],ok=i===q.correct_index;if(ok)score++;const opts=[...root.querySelectorAll('[data-option]')];opts.forEach((b,n)=>{b.disabled=true;b.classList.toggle('correct',n===q.correct_index);b.classList.toggle('wrong',n===i&&n!==q.correct_index);});const f=root.querySelector('[data-feedback]');f.hidden=false;f.innerHTML=`<strong>${ok?'CORRECT':'NOT QUITE'}</strong><p>${esc(q.explanation||'Review the concept and try again.')}</p>`;root.querySelector('[data-next]').disabled=false;await db.put('attempts',{question_id:q.id,date:new Date().toISOString().slice(0,10),subject:q.subject,chapter_id:q.chapter_id,context:'practice',selected:i,correct:ok,time_sec:0});const day=new Date().toISOString().slice(0,10),cur=await db.get('daily_activity',day);await db.put('daily_activity',{id:day,date:day,study_sec:cur?.study_sec||0,questions:(cur?.questions||0)+1,correct:(cur?.correct||0)+(ok?1:0),pyqs:cur?.pyqs||0,revisions:cur?.revisions||0,tests:cur?.tests||0,missions_done:cur?.missions_done||0});}
function finish(root){root.querySelector('[data-score]').textContent=`${score} / ${current.length}`;root.querySelector('[data-percent]').textContent=`${current.length?Math.round(score/current.length*100):0}%`;root.querySelector('[data-result]').hidden=false;root.querySelector('[data-test]').hidden=true;}
function start(root){const pool=filtered();current=[...pool].sort(()=>Math.random()-.5).slice(0,Math.min(10,pool.length));index=0;score=0;root.querySelector('[data-result]').hidden=true;root.querySelector('[data-test]').hidden=false;renderQuestion(root);}
export async function initMCQ(){const root=$('#mcqApp');if(!root)return;questions=await ensureSeed();root.innerHTML=`<div class="mcq-toolbar"><div><span class="lbl">PRACTICE FILTER</span><div class="mcq-filters"><select data-subject><option value="">All subjects</option>${SUBJ_KEYS.map(s=>`<option>${esc(s)}</option>`).join('')}</select><select data-difficulty><option value="">All difficulty</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select><button class="btn solid" data-start>START PRACTICE</button></div></div><div class="mcq-count"><span class="lbl">AVAILABLE</span><strong data-count>0</strong></div></div><section data-test hidden><div class="mcq-head"><span class="lbl" data-qno></span><span class="chip" data-meta></span></div><h2 data-qtext></h2><div class="mcq-options" data-options></div><div class="mcq-feedback" data-feedback hidden></div><div class="mcq-actions"><button class="btn" data-next>NEXT</button><button class="btn" data-finish>FINISH</button></div></section><section class="mcq-result" data-result hidden><span class="lbl">PRACTICE RESULT</span><strong data-score>0 / 0</strong><span data-percent>0%</span><button class="btn solid" data-restart>TRY AGAIN</button></section>`;
const updateCount=()=>root.querySelector('[data-count]').textContent=filtered().length;root.querySelector('[data-subject]').onchange=e=>{filter.subject=e.target.value;updateCount()};root.querySelector('[data-difficulty]').onchange=e=>{filter.difficulty=e.target.value;updateCount()};root.querySelector('[data-start]').onclick=()=>{if(!filtered().length){toast('No questions match these filters');return;}start(root)};root.querySelector('[data-options]').onclick=e=>{const b=e.target.closest('[data-option]');if(b)choose(root,Number(b.dataset.option))};root.querySelector('[data-next]').onclick=()=>{if(index<current.length-1){index++;renderQuestion(root)}else finish(root)};root.querySelector('[data-finish]').onclick=()=>finish(root);root.querySelector('[data-restart]').onclick=()=>start(root);updateCount();}
