import {db} from '../../services/db.js';
import {SUBJECTS,SUBJ_KEYS} from '../../data/syllabus.js';
import {esc,$} from '../../utils/dom.js';
const dayKey=d=>d.toISOString().slice(0,10);
const lastDays=n=>{const a=[];for(let i=n-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);a.push(dayKey(d))}return a};
export async function initAnalytics(){if(!document.querySelector('.analyticsApp'))return;render();}
async function render(){const roots=[...document.querySelectorAll('.analyticsApp')];if(!roots.length)return;const sessions=await db.all('study_sessions').catch(()=>[]),attempts=await db.all('attempts').catch(()=>[]),tests=await db.all('test_attempts').catch(()=>[]),activity=await db.all('daily_activity').catch(()=>[]);const totalSec=sessions.reduce((a,x)=>a+(x.duration_sec||0),0);const correct=attempts.filter(x=>x.correct===true).length;const acc=attempts.length?Math.round(correct/attempts.length*100):0;const submitted=tests.filter(x=>x.status!=='in_progress');const avg=submitted.length?Math.round(submitted.reduce((a,x)=>a+(x.max_score?x.score/x.max_score*100:0),0)/submitted.length):0;const days=lastDays(30);const byDate=new Map(activity.map(x=>[x.date,x]));const max=Math.max(1,...days.map(d=>byDate.get(d)?.study_sec||0));const html=`<div class="stats-grid"><div><span class="lbl">TOTAL STUDY</span><b>${Math.round(totalSec/3600*10)/10}h</b></div><div><span class="lbl">QUESTIONS</span><b>${attempts.length}</b></div><div><span class="lbl">ACCURACY</span><b>${acc}%</b></div><div><span class="lbl">TESTS</span><b>${submitted.length}</b></div><div><span class="lbl">AVG TEST</span><b>${avg}%</b></div></div><section class="analytics-block"><div class="section-head"><span class="lbl">30-DAY STUDY HEATMAP</span><span class="hint">CLICK A DAY FOR activity totals</span></div><div class="heatmap">${days.map(d=>{const x=byDate.get(d),m=x?.study_sec||0,l=m===0?0:m<1800?1:m<3600?2:m<7200?3:4;return `<button class="heat h${l}" title="${d}: ${Math.round(m/60)} min" aria-label="${d}: ${Math.round(m/60)} minutes">${new Date(d+'T12:00:00').getDate()}</button>`}).join('')}</div></section><section class="analytics-block"><span class="lbl">SUBJECT STUDY TIME</span><div class="bar-list">${SUBJ_KEYS.map(s=>{const sec=sessions.filter(x=>x.subject===s).reduce((a,x)=>a+(x.duration_sec||0),0);const pct=Math.round(sec/Math.max(1,totalSec)*100);return `<div class="bar-row"><span>${esc(s)}</span><i><b style="width:${pct}%"></b></i><strong>${Math.round(sec/360)/10}h</strong></div>`}).join('')}</div></section></div>`; roots.forEach(r=>r.innerHTML=html);
}
export async function renderTestHistory(){const root=$('#testHistoryApp');if(!root)return;const tests=await db.all('test_attempts').catch(()=>[]);tests.sort((a,b)=>String(b.submitted_at||b.started_at).localeCompare(String(a.submitted_at||a.started_at)));root.innerHTML=tests.length?`<div class="history-list">${tests.map(t=>`<article class="history-row"><span><b>${esc(t.status==='auto_submitted'?'Auto-submitted':'Completed test')}</b><small>${esc((t.submitted_at||t.started_at||'').slice(0,10))}</small></span><strong>${t.max_score?Math.round(t.score/t.max_score*100):0}%</strong><span>${Math.round((t.time_taken_sec||0)/60)} min</span></article>`).join('')}</div>`:`<div class="empty"><h3>No tests yet.</h3><p>Completed tests will appear here automatically.</p></div>`}
